name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install rclpy py_trees py_trees_ros

    - name: Run tests
      run: |
        sudo apt-get install ros-foxy-rclpy ros-foxy-sensor-msgs ros-foxy-geometry-msgs
        python -m unittest discover -s tests
